spring.application.name=citasbrillahogar



spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/citas_brillahogar_sena
spring.datasource.username=postgres
spring.datasource.password=W300430f
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
